console-sender-error: "&l&cEvent_Manager&r &c>> &fOnly player can use the command of this plugins"
event-already-exists: "&l&cEvent_Manager&r &c>> &fAn event with this name already exists"
event-created: "&l&cEvent_Manager&r &a>> &fEvent created successfully"
permissions-error: "&l&cEvent_Manager&r &c>> &fYou don't have the necessary permissions to run this command"
event-already-joined: "&l&cEvent_Manager&r &c>> &fYou have already entered the event"
event-joined: "&l&cEvent_Manager&r &9>> &fYou have successfully entered the event"
event-not-exists: "&l&cEvent_Manager&r &c>> &fThe indicated event does not exist"
event-leaved: "&l&cEvent_Manager&r &9>> &fYou have successfully leaved the event"
event-not-joined: "&l&cEvent_Manager&r &c>> &fYou are not present in the list of users participating in an event"
event-stared: "&l&cEvent_Manager&r &9>> &fThe event {event_name} is started!"
event-disbaned: "&l&cEvent_Manager&r &9>> &fYou successfully disbaned the event"
